-- MySQL Script generated by MySQL Workbench
-- Sun Nov 25 16:26:52 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema ticketitu
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ticketitu
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ticketitu` DEFAULT CHARACTER SET utf8 ;
USE `ticketitu` ;

-- -----------------------------------------------------
-- Table `ticketitu`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketitu`.`user` (
  `iduser` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `surname` VARCHAR(255) NULL,
  `login` VARCHAR(255) NULL,
  `password` VARCHAR(255) NULL,
  PRIMARY KEY (`iduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketitu`.`test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketitu`.`test` (
  `idtest` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `time` INT NULL,
  `difficulty` VARCHAR(255) NULL,
  PRIMARY KEY (`idtest`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketitu`.`question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketitu`.`question` (
  `idquestion` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(512) NULL,
  `type` VARCHAR(45) NULL,
  `A` VARCHAR(255) NULL,
  `B` VARCHAR(255) NULL,
  `C` VARCHAR(255) NULL,
  `D` VARCHAR(255) NULL,
  `E` VARCHAR(255) NULL,
  `F` VARCHAR(255) NULL,
  `right_answer` VARCHAR(255) NULL,
  `test_idtest` INT NOT NULL,
  PRIMARY KEY (`idquestion`, `test_idtest`),
  INDEX `fk_question_test1_idx` (`test_idtest` ASC),
  CONSTRAINT `fk_question_test1`
    FOREIGN KEY (`test_idtest`)
    REFERENCES `ticketitu`.`test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketitu`.`user_done_test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketitu`.`user_done_test` (
  `user_iduser` INT NOT NULL,
  `test_idtest` INT NOT NULL,
  `remain_time` INT NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`user_iduser`, `test_idtest`),
  INDEX `fk_user_has_test_test1_idx` (`test_idtest` ASC),
  INDEX `fk_user_has_test_user_idx` (`user_iduser` ASC),
  CONSTRAINT `fk_user_has_test_user`
    FOREIGN KEY (`user_iduser`)
    REFERENCES `ticketitu`.`user` (`iduser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_has_test_test1`
    FOREIGN KEY (`test_idtest`)
    REFERENCES `ticketitu`.`test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketitu`.`article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketitu`.`article` (
  `idarticle` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `img_url` VARCHAR(512) NULL,
  `song_url` VARCHAR(512) NULL,
  `weight_min` FLOAT NULL,
  `weight_max` FLOAT NULL,
  `height_min` FLOAT NULL,
  `height_max` FLOAT NULL,
  `order` VARCHAR(50) NULL,
  `graph_url` VARCHAR(512) NULL,
  `article` TEXT NULL,
  PRIMARY KEY (`idarticle`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketitu`.`done_question`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketitu`.`done_question` (
  `question_idquestion` INT NOT NULL,
  `user_done_test_user_iduser` INT NOT NULL,
  `user_done_test_test_idtest` INT NOT NULL,
  `answered` BINARY NULL,
  `answer` VARCHAR(45) NULL,
  PRIMARY KEY (`question_idquestion`, `user_done_test_user_iduser`, `user_done_test_test_idtest`),
  INDEX `fk_done_question_question1_idx` (`question_idquestion` ASC),
  INDEX `fk_done_question_user_done_test1_idx` (`user_done_test_user_iduser` ASC, `user_done_test_test_idtest` ASC),
  CONSTRAINT `fk_done_question_question1`
    FOREIGN KEY (`question_idquestion`)
    REFERENCES `ticketitu`.`question` (`idquestion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_done_question_user_done_test1`
    FOREIGN KEY (`user_done_test_user_iduser` , `user_done_test_test_idtest`)
    REFERENCES `ticketitu`.`user_done_test` (`user_iduser` , `test_idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ticketitu`.`test_has_article`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ticketitu`.`test_has_article` (
  `test_idtest` INT NOT NULL,
  `article_idarticle` INT NULL,
  PRIMARY KEY (`test_idtest`, `article_idarticle`),
  INDEX `fk_test_has_article_article1_idx` (`article_idarticle` ASC),
  INDEX `fk_test_has_article_test1_idx` (`test_idtest` ASC),
  CONSTRAINT `fk_test_has_article_test1`
    FOREIGN KEY (`test_idtest`)
    REFERENCES `ticketitu`.`test` (`idtest`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_test_has_article_article1`
    FOREIGN KEY (`article_idarticle`)
    REFERENCES `ticketitu`.`article` (`idarticle`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
